### ISSUE TITLE
license ??

### ISSUE THREAD

**Issue by islam2hamy** [bveenvliet/RoomDatabase#1]
license ??

**Comment by bveenvliet** [comment]
Apache 2.0

Feel free to send pull request

**Comment by islam2hamy** [comment]
I am asking because i need  to use it in my project

**Comment by bveenvliet** [comment]
Added LICENSE

**Comment by islam2hamy** [comment]
sorry about that , but i am new with this
so , now to use your code , i need to Fork it and begin my project ?
any thing else ?

**Comment by islam2hamy** [comment]
or just use it in my project without Fork it and make my project LICENSE Apache 2.0

**Comment by islam2hamy** [comment]
and what if i will include multiple open source source code in my project ?

**Comment by islam2hamy** [comment]
And what if i only need to use one file from your code?

**Comment by bveenvliet** [comment]
All terms and requirements are fully described in detail in the Apache LICENSE text. If you need further clarification, please check with a lawyer.
